version: '3.1'

services:
   db:
     image: mysql:5.7
     restart: unless-stopped
     volumes:
       - db:/var/lib/mysql
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   
   wordpress:
    image: wordpress:${WORDPRESS_VERSION}
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - wordpress:/var/www/html  
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
   
   wordpress-cli:
    image: wordpress:cli
    user: root
    volumes:
      - wordpress:/var/www/html
    command: sh -c "sleep 20 && 
                    wp core install --path=/var/www/html --url=localhost --title=${WORDPRESS_TITLE} --admin_user=${WORDPRESS_USER} --admin_password=${WORDPRESS_PASSWORD} --admin_email=${WORDPRESS_EMAIL} --allow-root && 
                    wp core version --allow-root && 
                    wp plugin install woocommerce --activate --allow-root --version=${WOOCOMMERCE_VERSION} && 
                    wp plugin install wirecard-woocommerce-extension --activate --allow-root --version=${WIRECARD_VERSION}"

volumes:
  wordpress:
  db:
